# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    command: sleep infinity
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer
    command: sleep infinity
    ports:
      - 8080:8080

